#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2011-2018 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/bashrc
#
# Description
#     Startup file for OpenFOAM-nrg
#     Sourced from ~/.bashrc
#     Should be usable by any POSIX-compliant shell (eg, ksh)
#
#------------------------------------------------------------------------------

export NRGFOAM_DIR=$(cd $(dirname ${BASH_SOURCE:-$0})/.. && pwd -P)

export NRGFOAM_ETC=$NRGFOAM_DIR/etc
export NRGFOAM_APP=$NRGFOAM_DIR/applications
export NRGFOAM_SRC=$NRGFOAM_DIR/src
export NRGFOAM_TUTORIALS=$NRGFOAM_DIR/tutorials
export NRGFOAM_UTILITIES=$NRGFOAM_APP/utilities
export NRGFOAM_SOLVERS=$NRGFOAM_APP/solvers

alias nrgfoam='cd $NRGFOAM_DIR'

#------------------------------------------------------------------------------
